version: '3.8'

services:
  pgvector:
    image: agnohq/pgvector:16
    container_name: pgvector
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgvolume:/var/lib/postgresql/data
    ports:
      - "5532:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    environment:
      DATABASE_URL: postgres://ai:ai@pgvector:5432/ai?sslmode=disable
    ports:
      - "8081:8081"
    depends_on:
      pgvector:
        condition: service_healthy

volumes:
  pgvolume:
